# See: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:

  build-docs:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.11.2

    steps:
      - checkout

      - run:
          name: Install pkg and dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade wheel setuptools pip
            pip install -r doc/requirements.txt
            pip install .

      - run:
          name: Build site
          command: |
            source venv/bin/activate
            # n = nitpicky (broken links), W = warnings as errors,
            # T = full tracebacks, keep-going = run to completion even with errors
            make -C doc/ SPHINXOPTS="-nWT --keep-going" html

      - store_artifacts:
          path: doc/_build/html

      - persist_to_workspace:
          root: doc/_build
          paths: html

  deploy-docs:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.11.2

    steps:
      - checkout

      - attach_workspace:
          at: doc/_build

      - run:
          name: Install deploy dependencies
          command: python3 -m pip install --user ghp-import

      - run:
          name: Configure git
          command: |
            git config --global user.name "ci-doc-deploy-bot"
            git config --global user.email "ci-doc-deploy-bot@nomail"
            git config --global push.default simple

            #      - add_ssh_keys:
            #          fingerprints:
            #            - e2:d9:9d:0c:a3:57:51:4b:36:da:a9:87:11:42:3d:c4
            #
            #      - run:
            #          name: Deploy via gh-pages
            #          command: |
            #            ghp-import -n -f -p -m "[skip ci] docs built of $CIRCLE_SHA1" doc/_build/html

workflows:
  version: 2
  build:
    jobs:
      - build-docs
      - deploy-docs:
          requires:
            - build-docs
          filters:
            branches:
              only: main
