name: test

on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package & test framework
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r neuromorpho_api/tests/requirements.txt
          python -m pip install .
          python -m pip list

      - name: Run tests
        run: |
          pytest --pyargs neuromorpho_api
